export const subtaskPlaceholders = [
   "e.g. Make coffee",
   "e.g. Drink coffee",
   "e.g. Smile",
   "e.g. Go for a walk",
   "e.g. Make another coffee",
   "e.g. Drink another coffee",
   "e.g. Smile again",
   "e.g. Go back to office",
   "e.g. How many more subtasks do you need?",
   "e.g. Sheesh! Are you building a reactor?",
   "e.g. Stop, please.",
   "e.g. Does it still fit?",
   "e.g. No way!",
   "e.g. What kind of monitor is this?",
   "",
   "We're no strangers to love",
   "You know the rules and so do I (do I)",
   "A full commitment's what I'm thinking of",
   "You wouldn't get this from any other guy",
   "",
   "I just wanna tell you how I'm feeling",
   "Gotta make you understand",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
   "",
   "We've known each other for so long",
   "Your heart's been aching, but you're too shy to say it (say it)",
   "Inside, we both know what's been going on (going on)",
   "We know the game and we're gonna play it",
   "",
   "And if you ask me how I'm feeling",
   "Don't tell me you're too blind to see",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
   "",
   "We've known each other for so long",
   "Your heart's been aching, but you're too shy to say it (say it)",
   "Inside, we both know what's been going on (going on)",
   "We know the game and we're gonna play it",
   "",
   "I just wanna tell you how I'm feeling",
   "Gotta make you understand",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
   "",
   "Never gonna give you up",
   "Never gonna let you down",
   "Never gonna run around and desert you",
   "Never gonna make you cry",
   "Never gonna say goodbye",
   "Never gonna tell a lie and hurt you",
];